name: PHPUnit
on:
  push:
    branches:
      - "main"
    paths:
      - "**.php"
      - "composer.json"
  pull_request:
    paths:
      - "**.php"
      - "composer.json"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2']
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: php vendor/bin/phpunit
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

      - uses: codecov/codecov-action@v3
        with:
          file: ./clover.xml
